server:
  port: 8080

spring:
  application:
    name: edusysproapi

  profiles:
    active: local

  #REST config
  data:
    rest:
      base-path: /api/v1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

# Development environment configuration
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/academic'
    username: 'postgres'
    password: 'password'

# Development environment configuration
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://34.168.154.185/academic'
    username: 'postgres'
    password: 'Password112022'

# Production environment configuration
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${DRIVER}
    url: 'jdbc:${DBMS}://${SERVER}:${PORT}/${DATABASE_NAME}'
    username: '${USERNAME}'
    password: '${PASSWORD}'